name: 'Get new version'
description: 'Get a new version number to bump up'
inputs:
    params: # other parameters
        description: 'parameters directly passed to entrypoint'
        required: false
        default: ''
outputs:
    newVersion:
        description: "new version number"

runs:
    using: 'docker'
    image: docker://fortune9/git-actions-env:latest
    entrypoint: 'bash -c ./update_version.sh'
    args:
        - ${{ inputs.params }}

