name: 'Get new version'
description: 'Get a new version number to bump up'
inputs:
    file: # version file
        description: 'current version file'
        required: false
        default: 'versions.json'
    entryPoint: # executable entrypoint
        description: 'Entrypoint for the docker image git-actions-env'
        required: false
        default: './entrypoint.sh'
outputs:
    newVersion:
        description: "new version number"

runs:
    using: 'docker'
    image: docker://fortune9/git-actions-env:latest
    entrypoint: $INPUT_ENTRYPOINT
    args:
        - ${{ inputs.file }}

