name: 'Get new version'
description: 'Get a new version number to bump up'
inputs:
    file: # version file
        description: 'current version file'
        required: false
        default: 'versions.json'
outputs:
    newVersion:
        description: "new version number"

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.file }}

