name: Build/push docker image

on:
    push:
        tags:
            - '*' # all tags without '/'

jobs:
    publish-docker:
        runs-on: ubuntu-latest
        steps:
            - name: just a test
              run: echo "${{ github.ref }}"


