name: Build/push docker image

on:
    push:
        #        tags:
        #    - '*' # all tags without '/'

jobs:
    publish-docker:
        env:
            IMAGE_NAME: fortune9/auto-hello
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: login dockerhub
              env:
                  DH_USER: ${{ secrets.DOCKERHUB_USER }}
                  DH_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
              run: |
                  docker login -u "$DH_USER" -p "$DH_PASS"
            - name: Get docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: "$IMAGE_NAME"
                  #- name: Build image
                  #run docker build . --file Dockerfile
            - name: Show docker meta
              env:
                  REPO_TAG: ${{ steps.meta.outputs.version }}
              run: |
                  echo "Tags: ${{ steps.meta.outputs.tags }}"
                  echo "Labels: ${{ steps.meta.outputs.labels }}"
            - name: Build and push docker
              run: |
                  echo "I can see REPO_TAG as $REPO_TAG"

