name: Build/push docker image

on:
    push:
        paths:
            - 'Dockerfile'
            - 'environment.yml'
            - '.github/workflows/build-docker.yml'

jobs:
    publish-docker:
        env:
            IMAGE_NAME: fortune9/auto-hello
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Login dockerhub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Add bin to PATH
              run: |
                  echo $(realpath bin) >>$GITHUB_PATH
            - name: set up R
              uses: r-lib/actions/setup-r@v2
            - name: install dependencies
              run: |
                  install.packages("jsonlite")
                  install.packages("optparse")
                  install.packages("glue")
              shell: Rscript {0}
            - name: Get version number
              id: get_versions
              run: |
                  # read the latest version first
                  content=$(cat versions.json)
                  content="${content//'%'/'%25'}"
                  content="${content//$'\n'/'%0A'}"
                  content="${content//$'\r'/'%0D'}"
                  #echo "::set-output name=versions::$content"
                  # set a new version
                  newVersion=$(bump_versions --zone dockerImage --version-pos file versions.json)
                  echo "newVersion=$newVersion" >> $GITHUB_ENV
            - name: Show version number
              id: show_version
              run: |
                  echo "New version is $newVersion"
            - name: Build and push docker
              run: |
                  #docker build -t $IMAGE_NAME:$REPO_TAG .
                  #docker image push $IMAGE_NAME:$REPO_TAG
                  res1=$(cat $GITHUB_PATH)
                  echo "I can see PATH as $res1"
                  echo "I can see PATH as $PATH"

