name: Scheduled actions

on:
    schedule:
        - cron: "0 17 * * *"

jobs:
    cron-job:
        runs-on: ubuntu-latest
        steps:
            - name: step 1
              id: step-id
              run: echo "This is a cron job"


