name: Semantic release
on:
    push:
        branches:
            - 'master'
            - 'feature/store-release-number'

jobs:
    create_release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup nodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: "16.15"
            - name: Install dependencies
              run: npm install @semantic-release/exec
            - name: Create a release
              id: create_release
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
            - name: Success
              run:
                  echo "New release is created: ${{ env.releaseV }}"
              env:
                  releaseV: ${{ steps.create_release.outputs.releaseVersion }}

