name: Semantic release
on:
    push:
        branches:
            - 'master'
            - 'feature/store-release-number'

jobs:
    create_release:
        runs-on: ubuntu-latest
        outputs:
            releaseV: ${{ steps.create_release.outputs.releaseVersion }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup nodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: "16.15"
            - name: Install dependencies
              run: npm install @semantic-release/exec
            - name: Create a release
              id: create_release
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
            - name: Post release
              if: steps.create_release.outputs.releaseVersion
              run: |
                  if [[ "$releaseV" == "" ]]; then
                    echo "No new release with empty version number"
                  else
                    echo "Store the version number $releaseV in job update_release_version"
                  fi
              env:
                  releaseV: ${{ steps.create_release.outputs.releaseVersion }}
    update_release_version:
        needs: create_release
        if: ${{ needs.create_release.outputs.releaseV != '' }}
        runs-on: ubuntu-latest
        steps:
            - name: Update version file
              run: echo "Updating version file"

