name: Semantic release
on:
    push:
        branches:
            - 'feature/semantic-release'

jobs:
    create_release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup nodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: "16.15"
            - name: Install dependencies
              run: npm install @semantic-release/exec
            - name: Create a release
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
            - name: Clean up
              run:
                  echo "Job done"
 
