name: test workflow

on: 
    push:
        - master
    pull_request:
        - master


jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello from github actions"
            - name: multiline script
              run: |
                  ls
                  echo $PATH
    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Notification
              run: |
                  echo "Changes to 'master' branch happened"
                  echo "Event: ${{ github.event_name }}"

